name: First_Pipeline2

on:
  push:
    branches:
      - main

jobs:
  Fi_Pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: First_step
        run: echo "vishal is a good guy. i'm printing this statment from inside a section from pipeline."

      - name: Second_Step
        run: whoami
