name: First_Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  F1_Pipeline:
  runs-on: ubuntu-latest
  steps:
    - name: First_step
      run: echo "vishal is a good guy. i'm printing this statment from inside a section from pipeline."


    - name: Second_Step
      run: whoami
